@startuml
class planning
class holidays
class week
class date
class tutorial
class lecture

planning "1" *-- "1" holidays
planning "1" *-- "*" week
week  "0..1" *-- "1" date
week  "0..1" *-- "1" tutorial
week  "0..1" *-- "1" lecture

@enduml