@startuml
/'A verifier le type de id, numero, photo'/
/'A verifier class visite et acte'/

class Cabinet {
  - nom : String
  - adresse : Adresse
  - infirmieres : List<Infirmiere>
  - patients : List<Patient>
}

class Adresse {
  - etage : String
  - numero : String/int
  - rue : String
  - codePostal : String
  - ville : String
}

class Infirmiere {
  - id : String/int
  - nom : String
  - prenom : String
  - photo : ????
}

class Patient {
  - nom : String
  - prenom : String
  - naissance : Date
  - numSecu : String/int
  - adresse : Adresse
  - infirmiereId : String/int
  - visites : List<Visite>
}

class Visite {
  - date : Date
  - intervenant = String  
  - actes : List<Acte>
}

class Acte {
  - id : String/int
}

' Relations
Cabinet "1" *-- "1" Adresse
Cabinet "1" *-- "3..*" Infirmiere
Cabinet "1" *-- "0..*" Patient
Patient "1" *-- "1" Adresse
Patient "1" *-- "0..*" Visite
Visite "1" *-- "1..*" Acte
@enduml